version: "3.9"

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://mongo:27017/devops
    depends_on:
      - mongo

  logger:
    build: ./logger
    ports:
      - "4000:4000"
    environment:
      - PORT=4000

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

  mongo:
    image: mongo
    ports:
      - "27017:27017"
