name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build backend image
        run: docker build -t taltal1131/backend ./backend

      - name: Push backend image
        run: docker push taltal1131/backend

      - name: Build frontend image
        run: docker build -t taltal1131/my-nginx-image ./frontend

      - name: Push frontend image
        run: docker push taltal1131/my-nginx-image
